### ISSUE TITLE
Questions!  Plex container and LB container in compose

### ISSUE THREAD

**Issue by NumberedThought** [magn2o/unicorn-docker#1]
Let me start by saying that you're a star for setting this up to start with.

Couple questions I have regarding your compose.  Do you need to setup the plex container first, I mean, comment out the LB, to start, tunnel in to plex and configure/claim?  Then uncomment the LB and get it up and running?

Also, I assume spinning up the transcoder on a separate instance and pointing it toward the advertise ip of the LB works fine?

I'm wondering if I use AWS that I can just point the transcoders toward the internal IP for security/ease.

Again, thanks for dockering this up.

**Comment by magn2o** [comment]
You can spool everything in the compose up, no need to comment anything out.  By default, the compose exposes 32400 so you can tunnel in and configure as per the [headless server instructions](https://github.com/plexinc/pms-docker#running-on-a-headless-server-with-container-using-host-networking).

As for remote transcoding, absolutely, that's the original intent -- to be able to spin up multiple remote transcoders on a whim as quickly as possible. Simply spin up the unicorn-transcoder container and point it to your public LB IP.
