### ISSUE TITLE
Not seeing any action from the transcoder

### ISSUE THREAD

**Issue by NumberedThought** [magn2o/unicorn-docker#2]
I have spun up the compose for plex and the LB.  Plex is accessible via the LB SERVER_PUBLIC address.  I've scanned in my media.
I then spun up my transcoder.  The transcoder can see the LB on it's advertise address and I see green background text
```  Versions:

  PLEX_BUILD=1.15.6.1079-78232c603
  CODECS_BUILD=392df4f-2233
  EAE_VERSION=eae-69c1de6-34
```

I then go to playback a file in plex from the LB public address.  Plex just spins.  The plex log doesn't show anything interesting, neither do the compose logs.

LoadBalancer/plex compose: https://gist.github.com/NumberedThought/8cd6efd2dec2cdd4bdf33412b23ae655

Transcoder Docker run:  https://gist.github.com/NumberedThought/ebf1b5e20b32b705c11f4cf565eebb7d
Transcoder docker logs show:
```
[cont-init.d] 01-install-transcoder: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

> UnicornTranscoder@2.0.0 start /opt/UnicornTranscoder
> node ./bin/www
```
LB docker logs show:
```
loadbalancer_1  | [cont-init.d] done.
loadbalancer_1  | [services.d] starting services
loadbalancer_1  | [services.d] done.
loadbalancer_1  |
loadbalancer_1  | > unicorn-load-balancer@2.0.0 start /opt/UnicornLoadBalancer
loadbalancer_1  | > node index.js
loadbalancer_1  |
```

Is there any logs I can get from the LB or the transcoder?
docker-compose for plex/LB: *<removed for privacy>*

Docker run for transcoder:  *<removed for privacy>*

Any help would be appreciated.

NOTE: I have yet to put it behind an SSL proxy.

**Comment by magn2o** [comment]
**Please sanitize your previously posted gists. Your IPs are visible, and I would assume you'd prefer they remain private.**

You can enable debugging by enabling specific environment variables on their respective containers:

**loadbalancer:**
~~~
DEBUG=Unicorn*
~~~

**transcoder:**
~~~
TRANSCODER_DEBUG=true
DEBUG=Unicorn*
~~~

That being said, at least from the logs above, there doesn't appear to be any incoming connections to the transcoder. ~~Have you deviated from any of the recommended port mappings?~~ Can you verify that the **Plex Transcoder** binary has been replaced in /usr/lib/plexmediaserver?

**Comment by NumberedThought** [comment]
Cleaned up private data.  Sorry about that, they were throwaways.

According to the loadbalancer log, the ffmpeg gets replaced:
```
loadbalancer_1  | > unicorn-ffmpeg@2.0.0 start /opt/UnicornFFMPEG
loadbalancer_1  | > pkg . -o "bin/Plex Transcoder"
loadbalancer_1  |
loadbalancer_1  | > pkg@4.4.0
loadbalancer_1  | > Fetching base Node.js binaries to PKG_CACHE_PATH
loadbalancer_1  |
loadbalancer_1  |
loadbalancer_1  |
loadbalancer_1  |
loadbalancer_1  | [cont-init.d] 02-install-ffmpeg: exited 0.
loadbalancer_1  | [cont-init.d] 03-remove-plex_relay: executing...
loadbalancer_1  | [cont-init.d] 03-remove-plex_relay: exited 0.
loadbalancer_1  | [cont-init.d] done.
```
I think it replaced it.  This is what the directory looks like
```
root@:/var/lib/docker/volumes/plex-lb_plex_binaries/_data# ls
 CrashUploader             'Plex DLNA Server'    'Plex Media Server'  'Plex Transcoder'      Resources  '~Plex Relay'
'Plex Commercial Skipper'  'Plex Media Scanner'  'Plex Script Host'   'Plex Tuner Service'   lib        '~Plex Transcoder'
root@:/var/lib/docker/volumes/plex-lb_plex_binaries/_data#
```
With the Debug added to the LB, I get this when attempting playback:
```
loadbalancer_1  | 2019-05-29T01:42:37.133Z UnicornLoadBalancer START plshisizddmdhjubq4w21og7 [DASH]
loadbalancer_1  | 2019-05-29T01:44:44.564Z UnicornLoadBalancer START plshisizddmdhjubq4w21og7 [DASH]
loadbalancer_1  | 2019-05-29T01:44:44.565Z UnicornLoadBalancer DELETE plshisizddmdhjubq4w21og7
loadbalancer_1  | 2019-05-29T01:44:47.357Z UnicornLoadBalancer SERVER plshisizddmdhjubq4w21og7 []
loadbalancer_1  | 2019-05-29T01:44:47.358Z UnicornLoadBalancer REDIRECT plshisizddmdhjubq4w21og7 [UNKNOWN]
loadbalancer_1  | 2019-05-29T01:46:54.332Z UnicornLoadBalancer SERVER plshisizddmdhjubq4w21og7 []
loadbalancer_1  | 2019-05-29T01:46:54.332Z UnicornLoadBalancer REDIRECT plshisizddmdhjubq4w21og7 [UNKNOWN]
```
But the Transcoder just sits there:
```

> UnicornTranscoder@2.0.0 start /opt/UnicornTranscoder
> node ./bin/www

2019-05-29T01:38:30.339Z UnicornTranscoder Starting EAE
2019-05-29T01:38:30.354Z UnicornTranscoder2:server Listening on port 32400
```

**Comment by magn2o** [comment]
Ok. Yes, the Plex Transcoder binary seems to be getting replaced so that's good.

First, is the transcoder reporting to the load balancer? You can check by visiting `http://<loadbalancer>:3001/api/stats`. Have you dropped port 32400 from the Plex container yet? If not, be absolutely sure that you are accessing Plex via the load balancer (i.e. `http://<loadbalancer>:3001/` and *not* via plex.tv -- otherwise requests would not get set to the remote transcoder (i.e. what you're currently experiencing). The core UnicornLoadBalancer setup instructions still apply -- once you've got the Plex container setup, port 32400 should be dropped. Usually you would do this via `iptables`, but in this case, with Docker you can just drop the exposed port to accomplish the same thing.

**Comment by NumberedThought** [comment]
I have not dropped the port.  Will do that now, but I was accessing the load balancer machine from the 3001 port.
The api/stats page seems to be pointing to my transcoder:

```
{"http://<transcoder-ip>:3000":{"name":"http://<transcoder-ip>:3000","sessions":[],"settings":{"maxSessions":10,"maxDownloads":10,"maxTranscodes":10},"url":"http://<transcoder-ip>:3000","time":1559096083,"score":0}}
```

**Comment by magn2o** [comment]
Have you checked what is reported back via Chrome DevTools or Safari JavaScript Console when playback is attempted?

Also, check to make sure that the route between the loadbalancer and transcoder is all good. 

i.e.
`docker exec loadbalancer nc -v <transcoder ip> 3000`

This should report back with:
`<transcoder> (<transcoder ip>:3000) open`

**Comment by NumberedThought** [comment]
And that was the problem.  Didn't have 3000 open on the transcoder
I've got playback!  Thanks So much!
